Repository COSSAS/SOARCA, pull requests merged in 2024-03, with the labels that each got.

#42 Use NewVariables
  internal/capability/http/http.go
  internal/capability/ssh/ssh.go
  internal/executer/executer.go
  test/integration/capability/http/http_integration_test.go
  test/integration/capability/ssh/ssh_integration_test.go
  test/unittest/cacao/variables_test.go
  test/unittest/decomposer/decomposer_test.go
  test/unittest/executor/executor_test.go
Labels: bug

#39 changed authinfo comparison from nil to empty struct
  utils/http/http.go
Labels: bug

#44 Feature/27 fin controller
  docker/mqtt/config/mosquitto.conf
  docker/mqtt/data/.gitkeep
  docker/mqtt/docker-compose.yml
  docker/mqtt/log/.gitkeep
  docs/content/en/docs/soarca-extentions/fin-protocol.md
  internal/capability/controller/controller.go
  models/fin/fin.go
  test/manual/capability/capability_controller_test.go
  test/unittest/capability/controller/controller_test.go
Labels: enhancement

#43 Refactor decomposer
  internal/decomposer/decomposer.go
  test/unittest/decomposer/decomposer_test.go
Labels: enhancement

#97 Minor typo in "core component overview" docs
  docs/content/en/docs/core-components/_index.md
Labels: documentation

#105 Feature/docs/101 reporting documentation (#101)
  docs/content/en/docs/core-components/reporting.md
Labels: documentation
