Repository COSSAS/SOARCA, pull requests merged in 2024-05, with the labels that each got.

#142 Added http content usage in http request
  test/unittest/utils/http/http_test.go
  utils/http/http.go
Labels: bug

#140 Bugfix/139 capabilities dont have the correct variable type on returning
  internal/capability/http/http.go
  internal/capability/openc2/openc2.go
  internal/capability/ssh/ssh.go
  internal/fin/protocol/protocol.go
  models/cacao/cacao.go
  test/unittest/finprotocol/finprotocol_test.go
Labels: bug

#145 Added http content variable replacement
  internal/executors/action/action.go
  test/unittest/executor/action/action_executor_test.go
Labels: enhancement

#138 Feature/116 add if condition executor
  docs/content/en/docs/core-components/executer.md
  internal/controller/controller.go
  internal/decomposer/decomposer.go
  internal/executors/condition/condition.go
  test/unittest/decomposer/decomposer_test.go
  test/unittest/executor/condition/condition_executor_test.go
  test/unittest/mocks/mock_executor/condition/condition_executor.go
  test/unittest/mocks/mock_utils/stix/mock_stix.go
  test/unittest/utils/stix/expression/comparison/comparison_test.go
  utils/stix/expression/comparison/comparison.go
Labels: enhancement, cacao

#98 Improved documentation
  docs/content/en/docs/contribution-guidelines/_index.md
  docs/content/en/docs/contribution-guidelines/code_of_conduct.md
  docs/content/en/docs/core-components/api-design.md
  docs/content/en/docs/core-components/modules.md
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/soarca-extensions/_index.md
  docs/hugo.toml
Labels: documentation

#127 Add fin-python-library page to docs
  docs/content/en/docs/soarca-extensions/fin-python-library.md
Labels: documentation, enhancement
